In [1]:
# Import dependencies
import pandas as pd
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt

#import warnings
#warnings.filterwarnings('ignore')

In [2]:
# Store filepath in a variable
file = Path("CVD_cleaned.csv")
diabetes_df = pd.read_csv(file, encoding="ANSI")
pd.set_option('display.max_columns', None)

In [3]:
diabetes_df['UniqueID'] = range(1, len(diabetes_df) + 1)

In [4]:
# shift column 'UniqueID' to first position 
#first_column = diabetes_df.pop('UniqueID') 
#diabetes_df.insert(0, 'UniqueID', first_column)

In [4]:
#diabetes_df.set_index('UniqueID', inplace=True)
diabetes_df

,General_Health,Checkup,Exercise,Heart_Disease,Skin_Cancer,Other_Cancer,Depression,Diabetes,Arthritis,Sex,Age_Category,Height_(cm),Weight_(kg),BMI,Smoking_History,Alcohol_Consumption,Fruit_Consumption,Green_Vegetables_Consumption,FriedPotato_Consumption,UniqueID
0,Poor,Within the past 2 years,No,No,No,No,No,No,Yes,Female,70-74,150.0,32.66,14.54,Yes,0.0,30.0,16.0,12.0,1
1,Very Good,Within the past year,No,Yes,No,No,No,Yes,No,Female,70-74,165.0,77.11,28.29,No,0.0,30.0,0.0,4.0,2
2,Very Good,Within the past year,Yes,No,No,No,No,Yes,No,Female,60-64,163.0,88.45,33.47,No,4.0,12.0,3.0,16.0,3
3,Poor,Within the past year,Yes,Yes,No,No,No,Yes,No,Male,75-79,180.0,93.44,28.73,No,0.0,30.0,30.0,8.0,4
4,Good,Within the past year,No,No,No,No,No,No,No,Male,80+,191.0,88.45,24.37,Yes,0.0,8.0,4.0,0.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308849,Very Good,Within the past year,Yes,No,No,No,No,No,No,Male,25-29,168.0,81.65,29.05,No,4.0,30.0,8.0,0.0,308850
308850,Fair,Within the past 5 years,Yes,No,No,No,No,Yes,No,Male,65-69,180.0,69.85,21.48,No,8.0,15.0,60.0,4.0,308851
308851,Very Good,5 or more years ago,Yes,No,No,No,Yes,"Yes, but female told only during pregnancy",No,Female,30-34,157.0,61.23,24.69,Yes,4.0,40.0,8.0,4.0,308852
308852,Very Good,Within the past year,Yes,No,No,No,No,No,No,Male,65-69,183.0,79.38,23.73,No,3.0,30.0,12.0,0.0,308853
308853,Excellent,Within the past year,Yes,No,No,No,No,No,No,Female,45-49,160.0,81.19,31.71,No,1.0,5.0,12.0,1.0,308854

In [5]:
# Create a new dataframe of only the consumption columns
consumption_df = diabetes_df[["UniqueID","Alcohol_Consumption", "Fruit_Consumption", "Green_Vegetables_Consumption",
                              "FriedPotato_Consumption"]]
consumption_df

,UniqueID,Alcohol_Consumption,Fruit_Consumption,Green_Vegetables_Consumption,FriedPotato_Consumption
0,1,0.0,30.0,16.0,12.0
1,2,0.0,30.0,0.0,4.0
2,3,4.0,12.0,3.0,16.0
3,4,0.0,30.0,30.0,8.0
4,5,0.0,8.0,4.0,0.0
...,...,...,...,...,...
308849,308850,4.0,30.0,8.0,0.0
308850,308851,8.0,15.0,60.0,4.0
308851,308852,4.0,40.0,8.0,4.0
308852,308853,3.0,30.0,12.0,0.0
308853,308854,1.0,5.0,12.0,1.0

In [6]:
# Create a new dataframe of only the non-consumption columns
health_df = diabetes_df[["UniqueID","General_Health","Checkup","Exercise","Heart_Disease","Skin_Cancer","Other_Cancer",
                         "Depression","Diabetes","Arthritis","Sex","Age_Category","Height_(cm)","Weight_(kg)",
                         "BMI","Smoking_History"]]
health_df

,UniqueID,General_Health,Checkup,Exercise,Heart_Disease,Skin_Cancer,Other_Cancer,Depression,Diabetes,Arthritis,Sex,Age_Category,Height_(cm),Weight_(kg),BMI,Smoking_History
0,1,Poor,Within the past 2 years,No,No,No,No,No,No,Yes,Female,70-74,150.0,32.66,14.54,Yes
1,2,Very Good,Within the past year,No,Yes,No,No,No,Yes,No,Female,70-74,165.0,77.11,28.29,No
2,3,Very Good,Within the past year,Yes,No,No,No,No,Yes,No,Female,60-64,163.0,88.45,33.47,No
3,4,Poor,Within the past year,Yes,Yes,No,No,No,Yes,No,Male,75-79,180.0,93.44,28.73,No
4,5,Good,Within the past year,No,No,No,No,No,No,No,Male,80+,191.0,88.45,24.37,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308849,308850,Very Good,Within the past year,Yes,No,No,No,No,No,No,Male,25-29,168.0,81.65,29.05,No
308850,308851,Fair,Within the past 5 years,Yes,No,No,No,No,Yes,No,Male,65-69,180.0,69.85,21.48,No
308851,308852,Very Good,5 or more years ago,Yes,No,No,No,Yes,"Yes, but female told only during pregnancy",No,Female,30-34,157.0,61.23,24.69,Yes
308852,308853,Very Good,Within the past year,Yes,No,No,No,No,No,No,Male,65-69,183.0,79.38,23.73,No
308853,308854,Excellent,Within the past year,Yes,No,No,No,No,No,No,Female,45-49,160.0,81.19,31.71,No

In [7]:
# Push the North Carolina DataFrame to a new CSV file
consumption_df.to_csv("consumptiondata.csv",
                  encoding="utf-8", index=False, header=True)

In [8]:
# Push the North Carolina DataFrame to a new CSV file
health_df.to_csv("healthdata.csv",
                  encoding="utf-8", index=False, header=True)