In [7]:
#importing dependencies
import pandas as pd
import numpy as np
import os
from pathlib import Path
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [11]:
# Loading data
file_path = Path("Resources/heart_cleaned.csv")
df_heart = pd.read_csv(file_path)

In [14]:
#Checking dataframe
df_heart.head()

,General_Health,Checkup,Exercise,Heart_Disease,Skin_Cancer,Other_Cancer,Depression,Diabetes,Arthritis,Sex,BMI,Smoking_History,Alcohol_Consumption,Fruit_Consumption,Green_Vegetables_Consumption,FriedPotato_Consumption,Age_Group
0,0,3,0,0,0,0,0,0,1,1,14.54,1,0.0,30.0,16.0,12.0,4
1,3,4,0,1,0,0,0,1,0,1,28.29,0,0.0,30.0,0.0,4.0,4
2,3,4,1,0,0,0,0,1,0,1,33.47,0,4.0,12.0,3.0,16.0,3
3,0,4,1,1,0,0,0,1,0,0,28.73,0,0.0,30.0,30.0,8.0,4
4,2,4,0,0,0,0,0,0,0,0,24.37,1,0.0,8.0,4.0,0.0,4

In [22]:
#checking the dataframe
df_heart.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308854 entries, 0 to 308853
Data columns (total 17 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   General_Health                308854 non-null  int64
 1   Checkup                       308854 non-null  int64
 2   Exercise                      308854 non-null  int64
 3   Heart_Disease                 308854 non-null  int64
 4   Skin_Cancer                   308854 non-null  int64
 5   Other_Cancer                  308854 non-null  int64
 6   Depression                    308854 non-null  int64
 7   Diabetes                      308854 non-null  int64
 8   Arthritis                     308854 non-null  int64
 9   Sex                           308854 non-null  int64
 10  BMI                           308854 non-null  float64
 11  Smoking_History               308854 non-null  int64
 12  Alcohol_Consumption           308854 non-null  float64
 13  Fruit_Consumption             308854 non-null  float64
 14  Green_Vegetables_Consumption  308854 non-null  float64
 15  FriedPotato_Consumption       308854 non-null  float64
 16  Age_Group                     308854 non-null  int64
dtypes: float64(5), int64(12)
memory usage: 40.1 MB

In [20]:
#checking rows and columns
df_heart.shape

(308854, 17)

In [15]:
# Get the target variable 
target = df_heart["Heart_Disease"]

In [21]:
# Get the features. 
heart_data = df_heart.drop("Heart_Disease", axis=1)
feature_names = heart_data.columns
feature_names

Index(['General_Health', 'Checkup', 'Exercise', 'Skin_Cancer', 'Other_Cancer',
       'Depression', 'Diabetes', 'Arthritis', 'Sex', 'BMI', 'Smoking_History',
       'Alcohol_Consumption', 'Fruit_Consumption',
       'Green_Vegetables_Consumption', 'FriedPotato_Consumption', 'Age_Group'],
      dtype='object')

In [23]:
#checking final dataframe
heart_data.head()

,General_Health,Checkup,Exercise,Skin_Cancer,Other_Cancer,Depression,Diabetes,Arthritis,Sex,BMI,Smoking_History,Alcohol_Consumption,Fruit_Consumption,Green_Vegetables_Consumption,FriedPotato_Consumption,Age_Group
0,0,3,0,0,0,0,0,1,1,14.54,1,0.0,30.0,16.0,12.0,4
1,3,4,0,0,0,0,1,0,1,28.29,0,0.0,30.0,0.0,4.0,4
2,3,4,1,0,0,0,1,0,1,33.47,0,4.0,12.0,3.0,16.0,3
3,0,4,1,0,0,0,1,0,0,28.73,0,0.0,30.0,30.0,8.0,4
4,2,4,0,0,0,0,0,0,0,24.37,1,0.0,8.0,4.0,0.0,4

In [24]:
#checking rows and columns
heart_data.shape

(308854, 16)

In [26]:
# Split data into training and testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(heart_data, target, random_state=65)

In [ ]:
# Support vector machine linear classifier
from sklearn.svm import SVC 
model = SVC(kernel='linear')
model.fit(X_train, y_train)

In [ ]:
#making predictions with test dataset
predictions = model.predict(X_test)
predictions

In [ ]:
# Model Accuracy
print('Test Acc: %.3f' % model.score(X_test, y_test))

In [ ]:
# Calculate the classification report
from sklearn.metrics import classification_report
predictions = model.predict(X_test)
print(classification_report(y_test, predictions,target_names=target_names))